@startuml
skinparam classAttributeIconSize 0

abstract class employee.Employee {
~job : Job
-firstName : String
-lastName : String
-gender : Gender
-age : int
{abstract} +work() : void
}

interface job.Job {
+work() : String
}

class employee.impl.Developer {
+work() : void
}

class job.impl.DeveloperJob {
-salary : int
+work() : String
}

class employee.impl.Janitor {
+work() : void
}

class job.impl.JanitorJob {
-salary : int
+work() : String
}

class employee.impl.Teacher {
+work() : void
}

class job.impl.TeacherJob {
-salary : int
+work() : String
}

class employee.impl.Doctor {
+work() : void
}

class job.impl.DoctorJob {
-salary : int
+work() : String
}

class employee.impl.Accountant {
+work() : void
}

class job.impl.AccountantJob {
-salary : int
+work() : String
}

enum employee.Gender {
MALE
FEMALE
}

job.Job <--* employee.Employee : has a
employee.Gender <- employee.Employee : uses

employee.Employee <|--- employee.impl.Developer
employee.Employee <|--- employee.impl.Janitor
employee.Employee <|--- employee.impl.Teacher
employee.Employee <|--- employee.impl.Doctor
employee.Employee <|--- employee.impl.Accountant

job.Job <|.... job.impl.DeveloperJob
job.Job <|.... job.impl.JanitorJob
job.Job <|.... job.impl.TeacherJob
job.Job <|.... job.impl.DoctorJob
job.Job <|.... job.impl.AccountantJob
@enduml